general 
{
	colors = true
	interval = 1
}

order += "disk /home"
order += "battery 0"
order += "volume master"
order += "tztime local" 
order += "tztime time"

battery 0 
{
	integer_battery_capacity = true
	format = "ϟ %percentage"
	low_threshold = 10
	threshold_type = percentage
}

tztime local
{
	format = "%a, %b %d"
}

tztime time
{
	format = "%l:%M"
}

disk "/home" 
{
	format = "%avail"
}

volume master
{
	format = "♩ %volume"
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}
